FROM ubuntu:14.04

MAINTAINER Alexej Kloos "alexejkloos@gmail.com"

# dependencies
RUN apt-get -qqy install wget software-properties-common

# sources
RUN wget -q -O - https://jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
RUN sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'

# software
RUN apt-get -qqy update
RUN apt-get -qqy install \
    jenkins

# start jenkins
RUN echo "service jenkins start" >> /run_all.sh; \echo "service jenkins start" >> /run_all.sh; \
  echo "tail -f /var/log/jenkins/jenkins.log;" >> /run_all.sh

# listen
EXPOSE 8080
CMD ["sh", "/run_all.sh"]
