#! /bin/bash
cd data/plugins/

wget https://updates.jenkins.io/latest/analysis-core.hpi
wget https://updates.jenkins.io/latest/jackson2-api.hpi
wget https://updates.jenkins.io/latest/junit.hpi
wget https://updates.jenkins.io/latest/mailer.hpi
wget https://updates.jenkins.io/latest/matrix-project.hpi
wget https://updates.jenkins.io/latest/structs.hpi
wget https://updates.jenkins.io/latest/script-security.hpi
wget https://updates.jenkins.io/latest/email-ext.hpi
wget https://updates.jenkins.io/latest/maven-plugin.hpi
wget https://updates.jenkins.io/latest/credentials.hpi
wget https://updates.jenkins.io/latest/git-client.hpi
wget https://updates.jenkins.io/latest/git.hpi
wget https://updates.jenkins.io/latest/github-api.hpi
wget https://updates.jenkins.io/latest/github.hpi
wget https://updates.jenkins.io/latest/ansicolor.hpi
wget https://updates.jenkins.io/latest/checkstyle.hpi
wget https://updates.jenkins.io/latest/cloverphp.hpi
wget https://updates.jenkins.io/latest/crap4j.hpi
wget https://updates.jenkins.io/latest/dry.hpi
wget https://updates.jenkins.io/latest/htmlpublisher.hpi
wget https://updates.jenkins.io/latest/jdepend.hpi
wget https://updates.jenkins.io/latest/plot.hpi
wget https://updates.jenkins.io/latest/pmd.hpi
wget https://updates.jenkins.io/latest/violations.hpi
wget https://updates.jenkins.io/latest/xunit.hpi
wget https://updates.jenkins.io/latest/warnings.hpi
wget https://updates.jenkins.io/latest/slack.hpi
wget https://updates.jenkins.io/latest/postbuild-task.hpi
wget https://updates.jenkins.io/latest/greenballs.hpi
wget http://archives.jenkins.io/plugins/email-ext/latest/email-ext.hpi
wget https://updates.jenkins.io/latest/token-macro.hpi
wget https://updates.jenkins.io/latest/ansible.hpi
wget https://updates.jenkins.io/latest/plain-credentials.hpi
wget https://updates.jenkins.io/latest/thinBackup.hpi
